name: ItemHistory
version: 0.1
author: stzups
api-version: 1.15
main: net.stzups.itemhistory.ItemHistory
website: stzups.net
commands:
  itemhistory:
    description: Main command for ItemHistory
    usage: /itemhistory <arguments>
    aliases: [ih]